# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'amplify-lib-ios-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for amplify-lib-ios-demo
    pod 'Amplify', '1.0.0'
    pod 'Amplify/Tools', '1.0.0'
    pod 'AmplifyPlugins/AWSAPIPlugin', '1.0.0'
    pod 'AmplifyPlugins/AWSDataStorePlugin', '1.0.0'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', '1.0.0'
    pod 'AWSPredictionsPlugin', '1.0.0'

end
